// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// sim
Rcpp::List sim(const Rcpp::List& params, const double Tmax);
RcppExport SEXP _DZepidemic_sim(SEXP paramsSEXP, SEXP TmaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List& >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< const double >::type Tmax(TmaxSEXP);
    rcpp_result_gen = Rcpp::wrap(sim(params, Tmax));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DZepidemic_sim", (DL_FUNC) &_DZepidemic_sim, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DZepidemic(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
