# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sim <- function(params, Tmax = 200.0) {
    .Call(`_DZepidemic_sim`, params, Tmax)
}

